image: node:latest

stages:
  - build&test
  - deploy_production

Test:
  stage: build&test
  script:
    - echo "Testing"
    - npm install
    - npm run test

Production:
  image: ruby:latest
  stage: deploy_production
  script:
    - echo "Deploying"
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=young-journey-50996 --api-key=$HEROKU_API_KEY
  only:
    - master